id: IF039D4B4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T10:06:05+00:00'
last_modified: '2022-06-07T14:10:37.042604+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27923
  title: འཇམ་དཔལ་གཤིན་རྗེ་དྲེགས་པ་འཇོམས་བྱེད་ཀྱི་ཆོས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    567B:
      image_group_id: I4525
      title: ''
      total_pages: 466
      order: 1
      base_file: 567B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
